### ISSUE TITLE
Thanks So Much For This - Some Suggesetions

### ISSUE THREAD

**Issue by WhyFenceCode** [saada2006/MinecraftShaderProgramming#5]
If you have the time in 2024, how about adding a one of these tutorials (I know they are a lot more work):
Alternate Sky
Volumetrics
Weather
Adding Reflections to the Glass
Sunrise and Sunset
Path Traced Lighting
Splitting Texels By Color
Just general documentation
Adding Bloom

**Comment by saadam1n** [comment]
I'm kind of forgetful. Perhaps could you send me a reminder here or on discord (@saad.amin) sometime during mid-January 2024?

**Comment by WhyFenceCode** [comment]
I might forget as well!

**Comment by catfoolyou** [comment]
I have used your shader tutorials to make my own (albeit crappy) shader [here](https://github.com/catfoolyou/Overhaul-shader). It has some code for fog, sky rendering and SSR that you might want to look at when making your own tutorial code, as well as moving the main shader code to deferred so that it will not conflict with rendering things through translucent blocks.

**Comment by WhyFenceCode** [comment]
Yea, I also realized how much work it is to do this stuff, so no pressure to do it.

**Comment by saadam1n** [comment]
Alright, I can start working on shader tutorials again, and after reviewing some of your suggestions, they seem pretty doable. However, there are many tutorials that already exist for these tutorials (e.g. if you want to implement an alternate sky or sunrise/sunset, you should take a look at scratchapixel's atmospheric scattering tutorial). Some other pieces of knowledge (like path-traced lighting) are more Minecraft shader-centeric as they require methods unique to Minecraft shader programming only (such as using the shadow pass to encode the world as a voxel grid). 

Regardless, I feel that the first thing I need to do is redo my existing tutorials, as I feel they could teach shader programming in a far more effective manner with better coding standards. Would you guys feel that I should redo my tutorials in a text-based format, or do them in a video format and upload them to YouTube? Or do you have a different idea?

**Comment by WhyFenceCode** [comment]
I like that idea, and would be willing to contribute what i can. I feel that you should do it in readme.mds like you did, and you can always make videos to go along with them later. I personaly found this format very helpfull

**Comment by WhyFenceCode** [comment]
I also feel that you should add reflections to your better lighting, as that brings stuff together a lot, but it is harder.

**Comment by catfoolyou** [comment]
Imo reading it off a page seems better for me, though I have no problems with a yt tutorial. Honestly, I think that the lighting model in the tutorials needs to be swapped for something better (such as the model used here https://github.com/saada2006/MinecraftShaders) because my shader looks really ugly in most scenarios using the tutorial lighting model (I never bothered to change it)

**Comment by MrDiver** [comment]
Any progress on this? I would like to contribute to the tutorials a bit, i would be really happy to make a somewhat more in-depth tutorial for the different techniques, we can also borrow and link to the other tutorials that you find useful.

Are you still in progress of writing and updating the current tutorial?

**Comment by saadam1n** [comment]
I'm currently working on revamping these tutorials and should have them updated within the next 1-2 weeks. Feel free to create a pull request in the meantime.

**Comment by WhyFenceCode** [comment]
Sounds awesome, just an idea for you, a small team of developers is in the process of making a new docs/guides site for the iris mod, and we need someone to write some basic tutorials. Would you be interested? test of the site is [here](https://shaders.properties/)

**Comment by saadam1n** [comment]
Yes, certainly!

**Comment by saadam1n** [comment]
I've just forked the documentation page, and I'll submit a pull request by next week.

**Comment by WhyFenceCode** [comment]
@saada2006 join the [Iris Discord #Docs Channel](https://discord.gg/the-iris-project-774352792659820594) to chat with the devs. Once your there i'll send you the sign up sheets for articles
